### ISSUE TITLE
Request parameters are chopped off after authentication redirect leading to incorrect URLs

### ISSUE THREAD

**Issue by abbhhiisseek** [AzureAD/azure-activedirectory-library-for-java#211]
Sample URL before authentication
http://localhost:8080/openTransfer.htm?reqId=T123

After authentication redirect, the parameter **reqId=T123** is chopped leaving only http://localhost:8080/openTransfer.htm

Can you please look into this?

**Comment by psignoret** [comment]
This is not an issue with the ADAL library, it's an issue (or rather, an unsupported feature) of the Azure AD service, which does not currently support query parameters in the redirect URI.

Is your query parameter a variable value (e.g. may change for different sign-ins)? Or a static value (e.g. `action=process_response`?

If it's a variable value, I would suggest using the `state` parameter of the authorization request. Whatever you stick in there will be included, unchanged, as the `state` parameter in the redirect back to your app. You should already be using `state` to [protect against CSRF attacks](https://tools.ietf.org/html/rfc6749#section-10.12), so one approach is to encode a JSON blob such as `{"reqId":"T123","csrf":"{nonce}"}` and send that (e.g. base64url-encoded) in the `state` parameter, where `reqId` is your parameter, and `csrf` is the value you're using for CSRF protection.

If it's a static value, I would suggest (if you can't or don't want to change the structure of the site) considering URL re-writing (e.g. [Apache](https://httpd.apache.org/docs/2.4/rewrite/remapping.html), [nginx](https://www.nginx.com/blog/creating-nginx-rewrite-rules/), [Tomcat](https://tomcat.apache.org/tomcat-8.0-doc/rewrite.html), [IIS](https://docs.microsoft.com/en-us/iis/extensions/url-rewrite-module/creating-rewrite-rules-for-the-url-rewrite-module)) so that, for example, `.../page/reqId/T123` (what you would register in Azure AD and what you would use as the `redirect_uri` in the auth. request) is rewritten to `.../page?reqId=T123` (what your web app expects).

**Comment by abbhhiisseek** [comment]
@psignoret Thank you.I'll try the above

**Comment by abbhhiisseek** [comment]
@sangonzal @psignoret
I am sending queryString in stateData in sendAuthRedirect method (Basic Filter) before authentication

    String state = "{\\"state\":\\"" + UUID.randomUUID().toString() +
    "\\",\\"queryString\\":\\"" + httpRequest.getQueryString() + "\\"}";
and retrieving it from State after authentication and setting it as servletRequest attribute in processAuthenticationData method (Basic Filter)

    JSONParser parser = new JSONParser();
    JSONObject stateJson = (JSONObject) parser.parse(params.get(STATE));
    String queryStr = stateJson.get("queryString").toString();
    if(queryStr != null ){
    	httpRequest.setAttribute("key", queryStr);
    }
Is this approach correct?

**Comment by vadivuk** [comment]
I have set the query params in state,hit sendauthRedirect and retrieved the same in processAuthenticationData. Not sure how to append the params with redirect url. If I try to append it, still the redirect url is not loaded with query params. I tried to set the params in query params object, still not working.

**Comment by sangonzal** [comment]
@abbhhiisseek Yes this is the right approach. Ensure that the state parameter is base64url-encoded. 

@vadivuk As psignoret stated above in his answer, appending query parameters to the redirect url is not supported by the AzureAD service.
