### ISSUE TITLE
It is not possible to get the Refreh Token

### ISSUE THREAD

**Issue by Aldi11** [AzureAD/azure-activedirectory-library-for-java#250]
Hi,

I,m using the adal4j 1.63 in order to connect with the CRM Dynamics 365. 
From my tests, i´ve seen that the refresh token is always null. 

My code looks like: 
               AuthenticationContext context = null;
		AuthenticationResult result = null;
		ExecutorService service = null;
		ClientCredential cc = new ClientCredential(APPIDURI, CLIENTSECRET);
		try {
			service = Executors.newFixedThreadPool(1);

			context = new AuthenticationContext(AUTHORITY, false, service);
			Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress(PROXY_ADDRESS, PROXY_PORT));
			context.setProxy(proxy);
			Future<AuthenticationResult> future = context.acquireToken(RESOURCE, cc, null);
			result = future.get();
		} finally {
			service.shutdown();
		}

		if (result == null) {
			throw new ServiceUnavailableException("authentication result was null");
		}
               String accessToken = result.getAccessToken();
		String refreshToken = result.getRefreshToken();

Can you please help me with this issue ? 
With the .Net library it works correctly.  

Best Regards

**Comment by SomkaPe** [comment]
Looks like you are acquiring token using client credential grant, so not on behalf of user, but on behalf of application itself. In this case STS did not return refresh token, main purpose of refresh token is to reduce number of times when user have to authorize application access, since in client cred flow user is not involved there is no much sense to use refresh token.

**Comment by Aldi11** [comment]
Hi. 
thank you very much for your response. 
I want to retrive the refresh token because i want too reduce number of times when user have to authorize application acces. 

How can i get it ?
