### ISSUE TITLE
Confusion arises when using Graph, Office combined permission to get access Token

### ISSUE THREAD

**Issue by ZhuXiaoBing-cn** [AzureAD/azure-activedirectory-library-for-java#300]
When I try to get an access token by using the combined Graph and Office permissions, I need to conduct administrator approval.
Here is my configuration on the portal,
![image](https://user-images.githubusercontent.com/71206407/102965089-164bb200-4528-11eb-92f5-21912a718cc8.png)

I used postman to get an access token, and the scope looks like this,
![image](https://user-images.githubusercontent.com/71206407/102965283-7fcbc080-4528-11eb-9378-2a217518bf07.png)

As you can see, I did not configure Calendar.Read in Microsoft Graph on portal. Sending a request results in the interface like this.

![image](https://user-images.githubusercontent.com/71206407/103050462-50bc5a00-45cf-11eb-8586-3a4c0b438031.png)

But if my scope is only Microsoft  Graph's Calendar.Read in the postman, it shows the following interface.
![image](https://user-images.githubusercontent.com/71206407/102965548-01235300-4529-11eb-90f5-036a22047bba.png)

![image](https://user-images.githubusercontent.com/71206407/103050563-9711b900-45cf-11eb-88ac-bfbe2756b397.png)

This is where I get confused.
Why is the interface approved by the administrator when graph and Office are combined, but the display consent interface when Graph is used alone?
Is this the effect of unconfigured Calendars.Read under Microsoft Graph?
Can you give me some help?

**Comment by sangonzal** [comment]
@ZhuXiaoBing-cn If you add `Calendars.Read` on the Azure portal, you'll see that Admin Consent is not required, and thus why you see the difference. See picture below. 
![GithubIssue](https://user-images.githubusercontent.com/35743865/103241300-c4889a80-4920-11eb-827a-cf575ef998e6.PNG)


When you add `activityfeed.Read` and `Calendars.Read`, you'll need admin approval, because `activityfeed.Read` requires it. If you remove `activityfeed.Read`, you no longer need admin consent, and user is able to consent via the UI that showed. 

By the way, ADAL has been deprecated, and we recommend that everyone uses [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-java/), which has an improved API and support for more scenarios.

**Comment by ZhuXiaoBing-cn** [comment]
@sangonzal Thank you for your reply and suggestions. These are helpful to me.
