### ISSUE TITLE
Authenticating users with their userName and password using the web application

### ISSUE THREAD

**Issue by narottam-singh-sp** [AzureAD/azure-activedirectory-library-for-java#60]
We have created and registered an web application on Azure and can do most of the operations. But we are facing issues while implementing the authentication for users with username and password and getting below errors.
While executing the PublicClient.java file it gives -
java.util.concurrent.ExecutionException: com.microsoft.aad.adal4j.AuthenticationException: {"error":"invalid_request","error_description":"AADSTS90014: The request body must contain the following parameter: 'client_secret.
I got to know from another post that the error is due to web application credentials and native application credentials should be used. Is there any way to authenticate users using web application credentials?

**Comment by RandalliLama** [comment]
@narottam-singh-sp Can you add more detail to what you are trying to do here?  What kind of app, and how are you getting the credentials?  Is this a web app?

**Comment by sagar-bhingare-sp** [comment]
@RandalliLama : Hi,
On behalf of @narottam-singh-sp , 
 We are using web app registered in the Azure AD to use Graph API. We are looking for the way to authenticate user, based on his login credentials using REST calls.

**Comment by RandalliLama** [comment]
@sagar-bhingare-sp I was afraid of that.  There is no way for you to do what you are after, and that is by design.  We do not want applications to collect usernames or passwords.  That is a risk to the users credentials and account.  Instead, you should use the regular OAuth flow in which you redirect the user to AAD in order to get an authorization code that you can then redeem for a token.  If you tell me what web stack you are running on I might be able to point you at a sample of this scenario.

**Comment by botiDev** [comment]
@RandalliLama : Hi,

I'm using Azure Active Directory to login-in to an application (Web application and/or web API) but i'm facing the same exception the guys above: "java.util.concurrent.ExecutionException: com.microsoft.aad.adal4j.AuthenticationException: {"error":"invalid_request","error_description":"AADSTS90014: The request body must contain the following parameter: 'client_secret' or 'client_assertion' ...". I'm wondering if you can provide me a sample of how to authenticate using OAuth flow. Thank you in advance.
